#
# brew/tasks/app.yml
# brew tasks for app
#
- name: Install homebrew packages
  command: brew bundle
  args:
    chdir: "{{ provision_path }}"

- name: update homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
