#
# brew/tasks/install.yml
# Install brew
#
- name: check exist brew command
  command: type brew
  register: exist_brew
  failed_when: exist_brew.rc not in [0, 1]
  changed_when: False

- name: brew install
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" < /dev/null
  when: exist_brew.rc == 1
