cask_args appdir: "/Applications"

brew "awscli"
brew "coreutils"
brew "ffmpeg"
brew "graphviz"
brew "mas"
brew "neovim"
brew "telnet"
brew "tmux"
brew "tree"
brew "jq"

cask "1password"
cask "alfred"
cask "bettertouchtool"
cask "docker"
cask "figma"
cask "google-chrome"
cask "iterm2"
cask "kap"
cask "karabiner-elements"
cask "kindle"
cask "ngrok"
cask "slack"
cask "visual-studio-code"
cask "zoom"
