cask_args appdir: "/Applications"

brew "asdf"
brew "awscli"
brew "coreutils"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "ghq"
brew "graphviz"
brew "mas"
brew "neovim"
brew "telnet"
brew "tmux"
brew "tree"
brew "jq"

# python
brew "ansible"
brew "ansible-lint"

cask "1password"
cask "1password-cli"
cask "bettertouchtool"
cask "claude-code"
cask "docker"
cask "discord"
cask "figma"
cask "google-chrome"
cask "iterm2"
cask "kap"
cask "karabiner-elements"
cask "kindle"
cask "ngrok"
cask "postman"
cask "slack"
cask "visual-studio-code"
cask "raycast"
cask "zoom"
