---
#
# dotfiles/tasks/install.yml
# Install dotfiles task
#
- name: Check dotfiles exists
  ansible.builtin.stat:
    path: "{{ dotfiles_path }}"
  register: dotfiles

- name: Install dotfiles
  when: not dotfiles.stat.exists
  tags: [skip_test]
  block:
    - name: Get dotfiles
      ansible.builtin.git:
        repo: https://github.com/winky/dotfiles.git
        version: HEAD # noqa: latest
        dest: "{{ dotfiles_path }}"

    - name: Install dotfiles
      ansible.builtin.command: make install
      args:
        chdir: "{{ dotfiles_path }}"
      register: install_dotfiles
      changed_when: install_dotfiles.rc != 0
