#
# dotfiles/tasks/install.yml
# Install dotfiles task
#
- name: Check dotfiles exists
  stat:
    path: "{{ dotfiles_path }}"
  register: dotfiles

- block:
  - name: Get dotfiles
    git:
      repo: "https://github.com/winky/dotfiles.git"
      dest: "{{ dotfiles_path }}"

  - name: Install dotfiles
    command: make install
    args:
      chdir: "{{ dotfiles_path }}"
  when: not dotfiles.stat.exists
  tags: [ skip_test ]
