---
#
# macos/tasks/default.yml
# macos defaults settings
#
- name: Set NSGlobalDomain
  community.general.osx_defaults:
    host: "{{ item.host | default() }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items: "{{ macos_global_defaults }}"
  tags:
    - setting

- name: Set com.apple defaults
  community.general.osx_defaults:
    host: "{{ item.host | default() }}"
    domain: com.apple.{{ item.domain }}
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value | default() }}"
  register: defaults_out
  with_items:
    - "{{ macos_apple_defaults }}"
  tags:
    - setting

- name: Set com.microsoft defaults
  community.general.osx_defaults:
    host: "{{ item.host | default() }}"
    domain: com.microsoft.{{ item.domain }}
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value | default() }}"
  register: defaults_out
  with_items:
    - "{{ macos_microsoft_defaults }}"
  tags:
    - setting
