---
#
# macos/tasks/main.yml
# main task for macos settings
#
- name: Network settings
  ansible.builtin.import_tasks: network.yml
  tags:
    - network
- name: System settings
  ansible.builtin.import_tasks: defaults.yml
  tags:
    - defaults
