---
#
# macos/tasks/network.yml
# macOS task for network settings
#
- name: Get current DNS servers
  ansible.builtin.command:
    cmd: networksetup -getdnsservers "{{ item }}"
  register: macos_current_dns
  changed_when: false
  failed_when: false
  loop: "{{ macos_network_service }}"
  tags: [dns, setting, skip_test]

- name: Set DNS servers
  ansible.builtin.command:
    cmd: networksetup -setdnsservers "{{ item.item }}" {{ macos_dns_servers | join(' ') }}
  loop: "{{ macos_current_dns.results | default([]) }}"
  loop_control:
    label: "{{ item.item }}"
  when: item.stdout_lines | sort != macos_dns_servers | sort
  changed_when: true
  tags: [dns, setting, skip_test]
