---
#
# github/tasks/main.yml
# configure task of github
#
- name: Check SSH key exists
  ansible.builtin.stat:
    path: "{{ github_ssh_key_path }}/{{ github_ssh_key_name }}"
  register: ssh_key

- name: Create SSH key for user
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    generate_ssh_key: true
    ssh_key_file: "{{ github_ssh_key_path }}/{{ github_ssh_key_name }}"
    ssh_key_bits: 4096
  when: not ssh_key.stat.exists
  tags:
    - ssh_key

- name: Read SSH public key
  ansible.builtin.command: cat "{{ github_ssh_key_path }}/{{ github_ssh_key_name }}.pub"
  register: ssh_pub_key
  when: not ssh_key.stat.exists
  failed_when: ssh_pub_key.rc not in [0, 1]
  changed_when: false

- name: Add public keys to github
  community.general.github_key:
    name: "{{ ansible_facts.hostname }}"
    token: "{{ github_access_token }}"
    pubkey: "{{ ssh_pub_key.stdout }}"
  when: not ssh_key.stat.exists
  tags: [skip_test]
