name: CI
on: pull_request

jobs:
  lint:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: init
        run: make init
      - name: ansible-lint
        run: ansible-lint -c ansible/.ansible-lint ansible/site.yml

  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: init
        run: make init
      - name: run ansible-playbook
        run: ansible-playbook ansible/site.yml -i ansible/inventories/macOS/local.yml --skip-tags="skip_test, brew-app"
      - run: sudo spctl --master-disable