name: CI
on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: init
      run: make init
    - name: install ansible-lint
      run: pip install ansible-lint
    - name: ansible-lint
      run: ansible-lint -c ansible/.ansible-lint ansible/site.yml
    - name: run ansible-playbook
      run: ansible-playbook ansible/site.yml -i ansible/inventories/macOS/local.yml --skip-tags="skip_test, brew-app"
    - name: install virtualbox
      run: brew cask install --force virtualbox