name: CI
on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: init
      run: make init
    - name: install ansible-lint
      run: pip install ansible-lint
    - name: ansible-lint
      run: ansible-lint ansible/site.yml